name: Build RTL8192EU for Lavender
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Toolchain
        run: |
          sudo apt update
          sudo apt install -y bc build-essential libncurses5-dev libssl-dev crossbuild-essential-arm64

      - name: Checkout Driver
        uses: actions/checkout@v3
        with:
          repository: Mange/rtl8192eu-linux-driver
          path: driver

      - name: Download Kernel Headers/Source
        run: |
          wget https://github.com/Team-420/android_kernel_xiaomi_lavender/archive/refs/tags/Nethunter-v3.5.tar.gz
          tar -xzf Nethunter-v3.5.tar.gz
          mv android_kernel_xiaomi_lavender-Nethunter-v3.5 kernel

      - name: Build Module
        run: |
          cd driver
          # Настройка параметров компиляции напрямую в команде
          make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- KSRC=../kernel -j$(nproc)

      - name: Upload Result
        uses: actions/upload-artifact@v3
        with:
          name: rtl8192eu-module
          path: driver/*.ko
